"""phase15 avatar detail columns for platform performance and edit metadata

Revision ID: 49da53f935d1
Revises: 75d43bffa97e
Create Date: 2026-08-24 22:09:06.898694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49da53f935d1'
down_revision: Union[str, Sequence[str], None] = '75d43bffa97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatar', sa.Column('description', sa.String(), nullable=True))
    op.add_column('avatar', sa.Column('performance_rank_android', sa.String(length=20), nullable=True))
    op.add_column('avatar', sa.Column('performance_rank_ios', sa.String(length=20), nullable=True))
    op.add_column('avatar', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('avatar', sa.Column('created_at_vrchat', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatar', 'created_at_vrchat')
    op.drop_column('avatar', 'version')
    op.drop_column('avatar', 'performance_rank_ios')
    op.drop_column('avatar', 'performance_rank_android')
    op.drop_column('avatar', 'description')
    # ### end Alembic commands ###
