"""add vrchat_notification and agent_command tables

Revision ID: 546c85c2aff8
Revises: e3e3a0d31fa5
Create Date: 2026-08-23 20:10:08.181046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546c85c2aff8'
down_revision: Union[str, Sequence[str], None] = 'e3e3a0d31fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_type', sa.String(length=30), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vrchat_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vrchat_notification_id', sa.String(length=64), nullable=False),
    sa.Column('pipeline_event', sa.String(length=30), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('sender_user_id', sa.String(length=64), nullable=True),
    sa.Column('sender_display_name', sa.String(length=100), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('raw_details', sa.String(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vrchat_notification_notification_type'), 'vrchat_notification', ['notification_type'], unique=False)
    op.create_index('ix_vrchat_notification_occurred_at', 'vrchat_notification', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_vrchat_notification_vrchat_notification_id'), 'vrchat_notification', ['vrchat_notification_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vrchat_notification_vrchat_notification_id'), table_name='vrchat_notification')
    op.drop_index('ix_vrchat_notification_occurred_at', table_name='vrchat_notification')
    op.drop_index(op.f('ix_vrchat_notification_notification_type'), table_name='vrchat_notification')
    op.drop_table('vrchat_notification')
    op.drop_table('agent_command')
    # ### end Alembic commands ###
