"""phase1: dashboard auth foundation

Revision ID: 6a82d2392381
Revises: 
Create Date: 2026-08-22 22:26:24.854375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a82d2392381'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('dashboard_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.String(length=20), nullable=False),
    sa.Column('discord_username', sa.String(length=100), nullable=False),
    sa.Column('discord_global_name', sa.String(length=100), nullable=True),
    sa.Column('discord_avatar_hash', sa.String(length=64), nullable=True),
    sa.Column('first_login_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_user_discord_user_id'), 'dashboard_user', ['discord_user_id'], unique=True)
    op.create_table('discord_allowlist_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_allowlist_entry_discord_user_id'), 'discord_allowlist_entry', ['discord_user_id'], unique=True)
    op.create_table('dashboard_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('dashboard_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_user_id'], ['dashboard_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_session_token_hash'), 'dashboard_session', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_session_token_hash'), table_name='dashboard_session')
    op.drop_table('dashboard_session')
    op.drop_index(op.f('ix_discord_allowlist_entry_discord_user_id'), table_name='discord_allowlist_entry')
    op.drop_table('discord_allowlist_entry')
    op.drop_index(op.f('ix_dashboard_user_discord_user_id'), table_name='dashboard_user')
    op.drop_table('dashboard_user')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
