"""phase7b: friend status_message

Revision ID: 6bca82855a55
Revises: b133a4a14452
Create Date: 2026-08-23 05:10:17.902960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bca82855a55'
down_revision: Union[str, Sequence[str], None] = 'b133a4a14452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('status_message', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend', 'status_message')
    # ### end Alembic commands ###
