"""add friend profile detail columns for table view

Revision ID: 75d43bffa97e
Revises: 546c85c2aff8
Create Date: 2026-08-23 20:42:09.573997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d43bffa97e'
down_revision: Union[str, Sequence[str], None] = '546c85c2aff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('trust_rank', sa.String(length=30), nullable=True))
    op.add_column('friend', sa.Column('languages', sa.String(length=255), nullable=True))
    op.add_column('friend', sa.Column('bio_links', sa.String(), nullable=True))
    op.add_column('friend', sa.Column('date_joined', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend', 'date_joined')
    op.drop_column('friend', 'bio_links')
    op.drop_column('friend', 'languages')
    op.drop_column('friend', 'trust_rank')
    # ### end Alembic commands ###
