"""phase3: avatars and tags

Revision ID: 7bf2b4423731
Revises: b6d76e9e759d
Create Date: 2026-08-22 23:01:09.233986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf2b4423731'
down_revision: Union[str, Sequence[str], None] = 'b6d76e9e759d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vrchat_avatar_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('thumbnail_image_url', sa.String(), nullable=True),
    sa.Column('performance_rank', sa.String(length=20), nullable=True),
    sa.Column('release_status', sa.String(length=20), nullable=False),
    sa.Column('updated_at_vrchat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_vrchat_avatar_id'), 'avatar', ['vrchat_avatar_id'], unique=True)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('avatar_tag',
    sa.Column('avatar_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avatar_id', 'tag_id')
    )
    op.create_index(op.f('ix_avatar_tag_tag_id'), 'avatar_tag', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avatar_tag_tag_id'), table_name='avatar_tag')
    op.drop_table('avatar_tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_avatar_vrchat_avatar_id'), table_name='avatar')
    op.drop_table('avatar')
    # ### end Alembic commands ###
