"""phase4: schedule events

Revision ID: 801ed3923b66
Revises: 7bf2b4423731
Create Date: 2026-08-22 23:33:05.979783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801ed3923b66'
down_revision: Union[str, Sequence[str], None] = '7bf2b4423731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('world_id', sa.String(length=100), nullable=True),
    sa.Column('world_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('vrchat_event_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatar.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vrchat_event_id')
    )
    op.create_index(op.f('ix_schedule_event_event_date'), 'schedule_event', ['event_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_event_event_date'), table_name='schedule_event')
    op.drop_table('schedule_event')
    # ### end Alembic commands ###
