"""phase11: game log agent token table

Revision ID: 96ca450906d1
Revises: b34cd4582510
Create Date: 2026-08-23 14:29:28.452634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ca450906d1'
down_revision: Union[str, Sequence[str], None] = 'b34cd4582510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_log_agent_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_log_agent_token_token_hash'), 'game_log_agent_token', ['token_hash'], unique=True)
    # ### end Alembic commands ###

    # 既存データの移行: 旧方式（app_settingに単一APIキーのハッシュを1個だけ保持）で
    # 発行済みのキーがあれば、新しいgame_log_agent_tokenテーブルへ1行として引き継ぐ
    # （そうしないと、既にペアリング済みのエージェントが突然認証エラーになってしまう）。
    op.execute(
        "INSERT INTO game_log_agent_token (token_hash, label) "
        "SELECT value, '移行された既存のAPIキー' FROM app_setting "
        "WHERE key = 'game_log_api_key_hash' AND value IS NOT NULL"
    )
    # 配布方式をダッシュボードのアップロード機能からGitHub Releasesへ変更したため、
    # ビルド管理用に使っていた設定値はもう使わない。
    op.execute(
        "DELETE FROM app_setting WHERE key IN "
        "('game_log_api_key_hash', 'game_log_agent_version', "
        "'game_log_release_upload_token_hash')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_log_agent_token_token_hash'), table_name='game_log_agent_token')
    op.drop_table('game_log_agent_token')
    # ### end Alembic commands ###
