"""phase7: friend online_state, self location tracking

Revision ID: b133a4a14452
Revises: c4c51ee90d56
Create Date: 2026-08-23 04:56:12.073405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b133a4a14452'
down_revision: Union[str, Sequence[str], None] = 'c4c51ee90d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('online_state', sa.String(length=10), server_default='offline', nullable=False))
    op.add_column('vrchat_session', sa.Column('self_location', sa.String(length=150), nullable=True))
    op.add_column('vrchat_session', sa.Column('self_world_id', sa.String(length=100), nullable=True))
    op.add_column('vrchat_session', sa.Column('self_world_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
    # 既存データの移行: is_online=Trueだった既存フレンドはonline_state='online'として扱う
    # （既存行はworldに滞在中かWeb/メニューのみかを区別する情報を持たないため、一律onlineとみなす）。
    op.execute("UPDATE friend SET online_state = 'online' WHERE is_online = 1")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vrchat_session', 'self_world_name')
    op.drop_column('vrchat_session', 'self_world_id')
    op.drop_column('vrchat_session', 'self_location')
    op.drop_column('friend', 'online_state')
    # ### end Alembic commands ###
