"""phase8: game log instances and events

Revision ID: b34cd4582510
Revises: 6bca82855a55
Create Date: 2026-08-23 10:01:02.625665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34cd4582510'
down_revision: Union[str, Sequence[str], None] = '6bca82855a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_log_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('world_id', sa.String(length=100), nullable=True),
    sa.Column('world_name', sa.String(length=255), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_log_instance_joined_at', 'game_log_instance', ['joined_at'], unique=False)
    op.create_table('game_log_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('player_vrchat_user_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['game_log_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_log_event_instance_time', 'game_log_event', ['instance_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_log_event_instance_time', table_name='game_log_event')
    op.drop_table('game_log_event')
    op.drop_index('ix_game_log_instance_joined_at', table_name='game_log_instance')
    op.drop_table('game_log_instance')
    # ### end Alembic commands ###
