"""phase2: vrchat session, friends, groups, presence history

Revision ID: b6d76e9e759d
Revises: 6a82d2392381
Create Date: 2026-08-22 22:43:24.689753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d76e9e759d'
down_revision: Union[str, Sequence[str], None] = '6a82d2392381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vrchat_user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('activity_status', sa.String(length=20), nullable=False),
    sa.Column('current_world_id', sa.String(length=100), nullable=True),
    sa.Column('current_world_name', sa.String(length=255), nullable=True),
    sa.Column('current_location', sa.String(length=150), nullable=True),
    sa.Column('current_avatar_thumbnail_url', sa.String(), nullable=True),
    sa.Column('last_seen_online_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_vrchat_user_id'), 'friend', ['vrchat_user_id'], unique=True)
    op.create_table('friend_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vrchat_group_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vrchat_group_id')
    )
    op.create_table('sync_cursor',
    sa.Column('resource_name', sa.String(length=50), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('resource_name')
    )
    op.create_table('vrchat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vrchat_user_id', sa.String(length=64), nullable=False),
    sa.Column('vrchat_display_name', sa.String(length=100), nullable=False),
    sa.Column('auth_cookie_encrypted', sa.String(), nullable=False),
    sa.Column('two_factor_cookie_encrypted', sa.String(), nullable=True),
    sa.Column('obtained_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_group_membership',
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friend.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['friend_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('friend_id', 'group_id')
    )
    op.create_index(op.f('ix_friend_group_membership_group_id'), 'friend_group_membership', ['group_id'], unique=False)
    op.create_table('friend_notification_pref',
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('notify_on_online', sa.Boolean(), nullable=False),
    sa.Column('notify_on_offline', sa.Boolean(), nullable=False),
    sa.Column('notify_on_world_change', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friend.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('friend_id')
    )
    op.create_table('friend_presence_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('world_id', sa.String(length=100), nullable=True),
    sa.Column('world_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friend.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_friend_presence_event_friend_time', 'friend_presence_event', ['friend_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_friend_presence_event_friend_time', table_name='friend_presence_event')
    op.drop_table('friend_presence_event')
    op.drop_table('friend_notification_pref')
    op.drop_index(op.f('ix_friend_group_membership_group_id'), table_name='friend_group_membership')
    op.drop_table('friend_group_membership')
    op.drop_table('vrchat_session')
    op.drop_table('sync_cursor')
    op.drop_table('friend_group')
    op.drop_index(op.f('ix_friend_vrchat_user_id'), table_name='friend')
    op.drop_table('friend')
    # ### end Alembic commands ###
