"""phase6: dashboard_user is_admin column

Revision ID: c4c51ee90d56
Revises: 324e05668581
Create Date: 2026-08-23 04:16:26.018573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c51ee90d56'
down_revision: Union[str, Sequence[str], None] = '324e05668581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_user', sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_user', 'is_admin')
    # ### end Alembic commands ###
