"""phase14: friend presence event previous_status column

Revision ID: ff8deb1a5e2c
Revises: 96ca450906d1
Create Date: 2026-08-23 17:18:39.693408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8deb1a5e2c'
down_revision: Union[str, Sequence[str], None] = '96ca450906d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_presence_event', sa.Column('previous_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friend_presence_event', 'previous_status')
    # ### end Alembic commands ###
